#
#
#
Type: 'word'

Reward:
  Money: 10000
  Cash: 0
  Commands:
    - 'give {player} diamond 64'

Tag:
  Enabled: false
  Name: 'miyukievents_word'
  Tag: '&c[Palavra]'

Cost: 0
Calls: 5
CallInterval: 15

Words:
  Random:
    Enabled: true
    Characters: '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    MaxCharacters: 30
  Words:
    - 'banana'
    - 'jaca'
    - 'melancia'
    - 'miyuki'

AutoStart:
  Enabled: true
  Times:
    - ''
  
Command:
  Permission: 'miyukievents.word'
  Names: ['palavra', 'word']

SubCommands:
  Start:
    Permission: 'miyukievents.word.start'
    Names: ['start', 'iniciar']




