#
#
#
Type: 'word'

Reward:
  Money: 10000
  Cash: 1
  Commands:
    - 'give {player} diamond 64'

Tag:
  Enabled: false
  Name: 'miyukievents_word'
  Tag: '&c[Palavra]'

Cost: 0
Calls: 5
CallInterval: 15

Words:
  Random:
    Enabled: true
    Characters: '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    MaxCharacters: 30
  Words:
    - 'miyuki'

AutoStart:
  Enabled: true
  Times:
    - ''
  
Command:
  Permission: 'miyukievents.word'
  Names: ['palavra', 'word']

SubCommands:
  Start:
    Permission: 'miyukievents.word.start'
    Names: ['start', 'iniciar']
  Stop:
    Permission: 'miyukievents.word.stop'
    Names: ['stop', 'parar']
  Reload:
    Permission: 'miyukievents.word.reload'
    Names: ['reload', 'recarregar']
  Help:
    # Este comando não necessita de nenhuma permissão, ao contrário do HelpAdmin.
    # É obrigatório que este comando tenha nomes, caso contrário será um nome padrão.
    Names:  ['help']
  HelpAdmin:
    # Este comando não necessita de nenhum nome.
    Permission: 'miyukievents.word.helpadmin'




