# Tipo do evento
Type: 'fastquiz'
# Nome do evento
Name: 'fastquiz'

# Permissão para participar do evento
Permission: 'miyukievents.fastquiz'
# Custo do evento (Esse evento ele não cobra para participar, ele só verifica se ele tem essa quantia)
# Não coloque valores negativos
Cost: 0

# Quantas chamadas terão
Calls: 5
# Quantos segundos cada chamada vai ter de intervalo
CallInterval: 15

# As perguntas
Questions:
  1:
    # A pergunta
    Question: 'Qual a capital do Brasil?'
    # A resposta
    Answer: 'Brasilia'
    # Ignorar a caixa alta/baixa?
    IgnoreCase: true
  2:
    Question: 'Qual a capital dos EUA?'
    Answer: 'Nova Iorque'
    IgnoreCase: false

# O prêmio
Reward:
  # Quantia de money (nunca coloque valor negativo)
  Money: 10000
  # Quantia de cash
  Cash: 0
  # Comandos que vão ser executados
  # {player} = nome do player
  Commands:
    - 'give {player} diamond 64'


# Sistema de tag
Tag:
  # Ativar essa tag?
  Enabled: false
  # O nome da tag
  Name: 'miyukievents_fastquiz'
  # Como ela vai ser mostrada?
  Tag: '&3[Fast-Quiz]'

# Comando
Command:
  # Permissão para usar ele
  Permission: 'miyukievents.fastquiz'
  # Aliases do comando
  Names: ['fastquiz', 'quizrapido']

SubCommands:
  # Iniciar o evento
  Start:
    Permission: 'miyukievents.fastquiz.start'
    Names: ['start', 'iniciar']
  # Parar o evento
  Stop:
    Permission: 'miyukievents.fastquiz.stop'
    Names: ['stop', 'parar']
  # Recarregar a config.yml do evento
  Reload:
    Permission: 'miyukievents.fastquiz.reload'
    Names: ['reload', 'recarregar']
  Help:
    # Este comando não necessita de nenhuma permissão, ao contrário do HelpAdmin.
    # É obrigatório que este comando tenha nomes, caso contrário será um nome padrão.
    Names:  ['help']
  HelpAdmin:
    # Este comando não necessita de nenhum nome.
    Permission: 'miyukievents.fastquiz.helpadmin'
