#
#
#
#
Database:
  # Tipos: MYSQL e SQLITE
  Type: SQLITE
  Host: localhost
  Port: 3306
  Database: MiyukiEvents
  Username: 'Username'
  Password: 'Password'
  # Aqui você poderá configurar algumas coisas do HikariCP.
  # Por padrão, já são dadas algumas configurações com base na documentação do hikari:
  # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
  Properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: true

Metrics: true

NumberFormatter:
  Format: '{number} {suffix}'
  GroupSeparator: '.'
  DecimalSeparator: ','
  # Em qual sufixo irá começar a formatação.
  # Caso seja 1, irá começar a formatar a partir do K.
  # Caso coloque 2, irá começar a formatar a partir do M.
  Start: 1
  Suffixes:
    - 'K'
    - 'M'
    - 'B'
    - 'T'
    - 'Q'
    - 'QI'
    - 'S'
    - 'SS'
    - 'O'
    - 'N'
    - 'D'
    - 'UN'
    - 'DD'
    - 'TR'
    - 'QT'
    - 'QN'
    - 'SD'
    - 'SPD'
    - 'OD'
    - 'ND'
    - 'VG'