#
#
#
#
Database:
  # Tipos: MYSQL e SQLITE
  Type: MYSQL
  Host: localhost
  Port: 3306
  Database: MiyukiEvents
  Username: 'Username'
  Password: 'Password'

Metrics: true

NumberFormatter:
  Format: '{number} {suffix}'
  GroupSeparator: '.'
  DecimalSeparator: ','
  # Em qual sufixo irá começar a formatação.
  # Caso seja 1, irá começar a formatar a partir do K.
  # Caso coloque 2, irá começar a formatar a partir do M.
  Start: 1
  Suffixes:
    - 'K'
    - 'M'
    - 'B'
    - 'T'
    - 'Q'
    - 'QI'
    - 'S'
    - 'SS'
    - 'O'
    - 'N'
    - 'D'
    - 'UN'
    - 'DD'
    - 'TR'
    - 'QT'
    - 'QN'
    - 'SD'
    - 'SPD'
    - 'OD'
    - 'ND'
    - 'VG'