#
#
#
#
Database:
  # Tipos: MARIADB (RECOMENDADO), MYSQL, H2, SQLITE
  Type: H2
  Host: localhost
  Port: 3306
  Database: MiyukiEvents
  Username: 'Username'
  Password: 'Password'
  # Aqui você poderá configurar algumas coisas do HikariCP.
  # Por padrão, já são dadas algumas configurações com base na documentação do hikari:
  # https://github.com/brettwooldridge/HikariCP/wiki/MySQL-Configuration
  Properties:
    cachePrepStmts: true
    prepStmtCacheSize: 250
    prepStmtCacheSqlLimit: 2048
    useServerPrepStmts: true
    useLocalSessionState: true
    rewriteBatchedStatements: true
    cacheResultSetMetadata: true
    cacheServerConfiguration: true
    elideSetAutoCommits: true
    maintainTimeStats: true

# Este sistema está em BETA, então tome cuidado em usar
# É necessário o uso de um banco de dados REDIS para utilizá-lo.
# Devido a transferência de itens ser perigosa, são realizados diversos backups do inventário do jogador.
# Esses backups podem ser encontrados na pasta BACKUPS
Bungeecord:
  Enabled: false
  # Nome do servidor em que este plugin está no momento.
  ServerName: 'rankup'
  # Marque esta opção caso o servidor em que este plugin esteja seja o servidor de minigames.
  # Ou seja, caso seja o servidor que irá receber os players do outro servidor para jogarem.
  MinigameServer: false
  # Servidor para que os jogadores irão.
  # Caso este plugin não esteja no servidor de minigames, você deve colocar o nome do servidor de minigames.
  # Caso este plugin esteja no servidor de minigames, você de ve colocar o lobby ou algum outro servidor.
  # O recomendavel é sempre mandar para o lobby!
  OutgoingServer: 'minigames'

  # É obrigatório o uso do Redis para que este sistema funcione.
  Redis:
    address: '127.0.0.1:6379'
    password: 'Password'




Metrics: true

NumberFormatter:
  Format: '{number}{suffix}'
  GroupSeparator: '.'
  DecimalSeparator: ','
  # Em qual sufixo irá começar a formatação.
  # Caso seja 1, irá começar a formatar a partir do K.
  # Caso coloque 2, irá começar a formatar a partir do M.
  Start: 1
  Suffixes:
    - 'K'
    - 'M'
    - 'B'
    - 'T'
    - 'Q'
    - 'QI'
    - 'S'
    - 'SS'
    - 'O'
    - 'N'
    - 'D'
    - 'UN'
    - 'DD'
    - 'TR'
    - 'QT'
    - 'QN'
    - 'SD'
    - 'SPD'
    - 'OD'
    - 'ND'
    - 'VG'