#
#
#
#
Database:
  # Tipos: MYSQL e SQLITE
  Type: MYSQL
  Host: localhost
  Port: 3306
  Database: MiyukiEvents
  Username: 'Username'
  Password: 'Password'

Commands: ['evento', 'event', 'game']

# Caso crie um evento customizado, registre-o aqui.
CustomEvents: []