Permission: 'miyukievents.word'
Cost: 0
Calls: 5
CallInterval: 15

Words:
  Random:
    Enabled: true
    Characters: '0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'
    MaxCharacters: 30
  Words:
    - ''
    - ''
    - ''

Reward:
  Money: 10000
  Cash: 0
  Commands:
    - 'give {player} diamond 64'

Tag:
  Enabled: false
  Name: 'miyukievents_word'
  Tag: '&c[Palavra]'