Type: 'lottery'
Name: ''

Permission: 'miyukievents.lottery'
Cost: 0
Calls: 5
CallInterval: 15

MinNumber: 1
MaxNumber: 1000

Reward:
  Money: 10000
  Cash: 0
  Commands:
    - 'give {player} diamond 64'

Tag:
  Enabled: false
  Name: 'miyukievents_lottery'
  Tag: '&b[Loteria]'