Type: 'fastclick'
Name: 'fastclick'

Cost: 0

# Em segundos
ExpireTime: 200

Messages:
  1: 'Clique <click:run_command:/fastclick {id}>AQUI</click> para ganhar'
  2:
    - 'Clique no telefone para ganhar:'
    - 'BANANA <click:run_command:/fastclick {id}>TELEFONE</click> CACHORRO'

Reward:
  Money: 10000
  Cash: 0
  Commands:
    - 'give {player} diamond 64'

Tag:
  Enabled: false
  Name: 'miyukievents_fastclick'
  Tag: '&5[FastClick]'

# Comando
Command:
  # Permissão para usar ele
  Permission: 'miyukievents.fastclick'
  # Aliases do comando
  Names: ['fastclick']

SubCommands:
  # Iniciar o evento
  Start:
    Permission: 'miyukievents.fastclick.start'
    Names: ['start', 'iniciar']
  # Parar o evento
  Stop:
    Permission: 'miyukievents.fastclick.stop'
    Names: ['stop', 'parar']
  # Recarregar a config.yml do evento
  Reload:
    Permission: 'miyukievents.fastclick.reload'
    Names: ['reload', 'recarregar']
  Help:
    # Este comando não necessita de nenhuma permissão, ao contrário do HelpAdmin.
    # É obrigatório que este comando tenha nomes, caso contrário será um nome padrão.
    Names:  ['help']
  HelpAdmin:
    # Este comando não necessita de nenhum nome.
    Permission: 'miyukievents.fastclick.helpadmin'